# This workflow will build a docker image from develop and pushing it to docker hub with the tag `nightly`
# Its uses JIB to build and push the Docker image

name: Build and push nightly develop

on:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'develop'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Execute unit tests
      run: mvn -B test
    - name: build docker image and push to dockerhub with JIB
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: mvn compile jib:build -Dimage=franco87/practica-ci:nightly -Djib.to.auth.username=$DOCKERHUB_USER	 -Djib.to.auth.password=$DOCKERHUB_PASSWORD

