# This workflow will build a docker image from develop and pushing it to docker hub with the :develop tag

name: Build and push develop

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Execute unit tests
      run: mvn -B test
    - name: build docker image and push to dockerhub with JIB
      run: mvn compile jib:build -Dimage=franco87/practica-ci:develop -Djib.to.auth.username=$DOCKERHUB_USER	 -Djib.to.auth.password=DOCKERHUB_PASSWORD

