# This workflow will execute tests on all branches except master and develop

name: Build branch and publish artifact

on:
  # Run tests for any PRs.
  pull_request:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: build
      run: mvn -B package --file pom.xml
    - name: Get branch name
      id: branch_name
      run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
    - uses: actions/upload-artifact@v2
      with:
        name: ${{steps.branch_name.outputs.branch_name}}.jar
        path: target/**/*.jar
