# This workflow will build a docker image from master where a tag is created. The image will be pushed to docker hub

name: Build and push nightly develop

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Execute unit tests
      run: mvn -B test
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: build docker image and push to dockerhub with JIB
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: mvn compile jib:build -Dimage=franco87/practica-ci:$RELEASE_VERSION -Djib.to.auth.username=$DOCKERHUB_USER	 -Djib.to.auth.password=$DOCKERHUB_PASSWORD

