# This workflow will execute tests and package when a pull request is issued. Will publish the artefact into the CI repository

name: Build branch and publish artifact

on:
  # Run tests for any PRs.
  push:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        curl -XPOST -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/franco87/fj.franco.2019-CD/dispatches --data '{"event_type": "build_application"}'
