# This workflow will build a docker image from master when a tag is created. The image will be pushed to docker hub
# Its uses JIB to build and push the Docker image

name: Build and push release

on:
  push: # se podría usar `release` pero de esta forma puedo obtener sencillamente el tag para el Docker
    tags:
      - '*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Execute unit tests
      run: mvn -B test
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: build docker image and push to dockerhub with JIB
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: mvn compile jib:build -Dimage=franco87/practica-ci:$RELEASE_VERSION -Djib.to.auth.username=$DOCKERHUB_USER	 -Djib.to.auth.password=$DOCKERHUB_PASSWORD

